plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
    id 'maven-publish'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = mod_id
}

sourceSets {
    // include generated resources
    main.resources { srcDir 'src/generated/resources' }
}

repositories {
    mavenCentral()
}

loom {
    accessWidenerPath = file("src/main/resources/dragonmounts.accesswidener")
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property "version", rootProject.version
    inputs.property "minecraft_version", rootProject.minecraft_version
    inputs.property "loader_version", rootProject.loader_version
    inputs.property "mod_id", rootProject.mod_id
    inputs.property "mod_name", rootProject.mod_name
    inputs.property "mod_version", rootProject.mod_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": rootProject.version,
                "minecraft_version": rootProject.minecraft_version,
                "loader_version": rootProject.loader_version,
                "mod_id": rootProject.mod_id,
                "mod_name": rootProject.mod_name,
                "mod_version": rootProject.mod_version
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }

    // data-gen artifacts aren't necessary in release builds.
    exclude('com/github/kay9/dragonmounts/data/providers/**')
    exclude('.cache')
}

tasks.withType(JavaCompile).configureEach {
    it.options.release.set(Integer.parseInt(project.java_version))
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
