# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.2

# Mod Properties
mod_id=dragonmounts
mod_name=Dragon Mounts: Legacy
mod_version=26.2
maven_group=com.github.kay9.dragonmounts
archives_base_name=dragonmounts

# Dependencies
fabric_version=0.152.1+26.2

# Java
java_version=25
